site_name: Overall Architecture
copyright: Copyright &copy; 2023 - Sofka
repo_url: https://github.com/sofka-practices/overall-arch/
repo_name: GitHub
site_url: https://sofka-practices.github.io/overall-arch/
edit_uri: edit/main/docs/
nav:
    - Home: 'index.md'
    - Atributos de calidad: 'atributos.md'
    - Tacticas de Arquitectura: 'tacticas.md'
    - Tecnologias Recomendas: 'enfoque.md'
    - Principios Fundamentales: 'principios.md'
    - Arquitectura Reactiva: 'reactividad.md'
    - Arquitectura Cloud: 'cloud.md'

theme:
  language: es
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  font:
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black

    
  features:
    - navigation.indexes
    - navigation.footer
    - header.autohide
    - content.code.annotate 
    - content.code.select
    - content.code.copy
    - content.action.edit
    - search.share


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  version:
    provider: mike
